### ISSUE TITLE
Testing workflow - Needs env variables for settings.py file

### ISSUE THREAD

**Issue by cashmy** [cashmy/pronto_npc_backend#3]
The Djano testing workflow fails when it trys to connect to the DBNAME - 
At this early stage of development the database only resided on my development box. 
No initial deployment yet of the MySQL db.
No docker image to pull and run against (yet).

**Comment by cashmy** [comment]
Okay, let's get your GitHub Actions workflow set up to handle those database credentials securely!

The config("DB_NAME"), config("DB_USER"), etc., calls in your settings.py are using the python-decouple library. This library looks for these values primarily in environment variables or a .env file. In the GitHub Actions runner environment, neither of these will be automatically configured with your specific database credentials.

The best practice for handling sensitive information like database passwords in GitHub Actions is to use GitHub Secrets.

Here's how you can set it up:

1. Add Secrets to your GitHub Repository:

   - Go to your repository on GitHub.
   - Click on the "Settings" tab.
   - In the left sidebar, navigate to "Secrets and variables" -> "Actions".
   - Click the "New repository secret" button for each credential you need. Create secrets with the following names (matching what python-decouple expects):
         - DB_NAME
         - DB_USER
         - DB_PASSWORD
         - DB_HOST (If it's not localhost for your CI tests. If your tests can run against a local DB within the runner, you might skip this or set it differently. Often for CI, you might use a service container or a different DB like SQLite).
         - DB_PORT (If it's not the default 3306).
   - Paste the corresponding value for each secret and save it.

2. Update your GitHub Actions Workflow: Modify your .github/workflows/django-ci.yml file to pass these secrets as environment variables to the step that runs your tests. The python-decouple library will then automatically pick them up.

Here's the updated workflow:

``` 
# .github/workflows/django-ci.yml

name: Django CI

on:
  push:
    branches: [ main ] # Trigger the workflow on push events to the main branch
  workflow_dispatch: {} # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Check out code
      uses: actions/checkout@v4 # Action to check out the repository code

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5' # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure python-decouple is installed if it's not already in requirements.txt
        # pip install python-decouple
        pip install -r requirements.txt # Install dependencies from requirements.txt

    - name: Run Django Tests
      # Add the 'env' block here to expose secrets as environment variables
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }} # Use localhost or a service container hostname if applicable
        DB_PORT: ${{ secrets.DB_PORT }} # Use the standard port or your secret
        # You might need to set SECRET_KEY as well if it's also managed by decouple
        # SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py test # Execute the Django test suite
```
